title: A Sublime Dive into Gemini CLI
description: Master Gemini CLI using Sublime Text
url: "https://flashmodel.github.io"
baseurl: "/sublime-gemini-book"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
navigation:
  - text: Get Started with Gemini CLI
    url: /
  - text: overview
    url: /get-started/overview/
  - text: installation
    url: /get-started/installation/
  - text: authentication
    url: /get-started/authentication/
  - text: quickstart
    url: /get-started/quickstart/
  - text: basic usage
    url: /basic-usage/
  - text: context menu
    url: /context-menu/
  - text: command palette
    url: /command-palette/
